<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-118273O" ignored="1" name="Hubspot Regressiontest --ff" tests="4" failures="1" timestamp="2020-10-04T03:35:20 IST" time="101.612" errors="0">
  <testcase name="verifyTitleTest" time="6.053" classname="com.qa.hubspot.test.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [HubSpot Login234] but found [HubSpot Login]">
      <![CDATA[java.lang.AssertionError: expected [HubSpot Login234] but found [HubSpot Login]
at com.qa.hubspot.test.LoginPageTest.verifyTitleTest(LoginPageTest.java:53)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verifyTitleTest -->
  <testcase name="verifySignupTest" time="6.102" classname="com.qa.hubspot.test.LoginPageTest"/>
  <testcase name="verifyForgotPasswordTest" time="5.241" classname="com.qa.hubspot.test.LoginPageTest"/>
  <testcase name="verifyLoginTest" time="7.529" classname="com.qa.hubspot.test.LoginPageTest"/>
  <testcase name="negativeLoginTest" time="0.0" classname="com.qa.hubspot.test.LoginPageTest">
    <ignored/>
  </testcase> <!-- negativeLoginTest -->
</testsuite> <!-- Hubspot Regressiontest -ff -->
